```{r}
#| cache: true
```

Summarize and interpret these neuropsychological test scores as if you are an
experienced clinical neuropsychologist. For scores that are below average,
give a brief example of how this could impact the patient's daily life and functioning. Organize your
summary and interpretation from scores that are above average to below average to delineate
relative strengths and weaknesses. The patient is an {{adult}} {{male}}.

<<START>>
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
 Orthographic lexicon, or sight vocabulary fluency was Below Average. 
A composite score of decoding and comprehension that balances word-level and text-level reading skills was Below Average. 
Single word reading/decoding of a list of regular and irregular words was Below Average. 
Reading comprehension skills at the level of word, sentence, and passage was Below Average. 
A composite estimate of decontextualized phonic decoding and word reading skills was Below Average. 
A clinically sensitive composite score for identifying risk for dyslexia among students was Below Average. 
Phonic decoding skills as assessed by reading aloud a list of pseudowords was Exceptionally Low. 
Phonic decoding fluency was Exceptionally Low.
