---
title-meta: adhd
---

On parent/observer ratings of adult ADHD symptoms and impairments, completed by Mr. Lopez's mother, high scores were reported in Inattention/Memory Problems, Hyperactivity/Restlessness, and Impulsivity/Emotional Lability, which suggests difficulties with concentration, completing tasks, restlessness, and impulsiveness. Mr. Lopez's score for Problems with Self-Concept was average, indicating typical social relationships, self-esteem, and self-confidence. The DSM-5 subscales indicate that Mr. Lopez behaves mildly atypically when it comes to Inattentive Symptoms, Hyperactive-Impulsive Symptoms, and Total ADHD Symptoms, which is consistent with an ADHD diagnosis. Finally, a global adult ADHD Index suggested that Mr. Lopez is "at risk" for ADHD.

Observer ratings of Mr. Lopez's executive functioning were Below Average in planning (i.e., developing and implementing strategies to accomplish tasks), self-monitoring (i.e., evaluating own behavior), attention (i.e., avoiding distractions), inhibitory control (i.e., controlling behavior or impulses), organization (i.e., managing personal effects), and emotion regulation (i.e., controlling and managing emotions).
