```{r}
#| cache: true
```

<<PROMPT>>

Summarize and interpret these neuropsychological test scores as if you are an
experienced clinical neuropsychologist. For scores that are below average,
give a brief example of how this could impact the patient's daily life and functioning. Organize your
summary and interpretation from scores that are above average to below average to delineate
relative strengths and weaknesses.

<<START>>

Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
 Total number of repetitive response errors was High Average. 
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was High Average. 
A measure of both attentional capacity and working memory was Average. 
Basic psychomotor processing speed was Average. 
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average. 
Retrieval fluency, ideational fluency, and generativity was Average. 
Orientation to person, place, time, and situation was intact. 
Working memory for orally presented information was Average (5 digits backward). 
Self-monitoring and perseverative tendencies was Average. 
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average. 
Maintenance and resequencing of progressively lengthier number and letter strings in working memory was Average. 
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range. 
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the Average range. 
Psychomotor speed was Average. 
Efficiency of psychomotor speed, visual scanning ability, and visual-motor coordination was Average. 
An overall measure of efficiency in performing a selective attention letter cancellation task was Average. 
Total number of intrusive response errors was Average. 
Auditory attentional capacity, or how much information can be processed at once was Low Average. 
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Low Average range. 
Auditory attentional capacity was Low Average (6 digits forward).
