---
title-meta: Recommendations
---

## Recommendations for Medical/Healthcare

Based on the results of the assessment, Dr. Dre recommends that Nestor receive the following services:

- Individualized instruction in reading
- Remedial instruction in math and writing
- Behavioral therapy to address his attention and behavioral problems
- Family therapy to address his family history of mental illness
- Dr. Dre also recommends that Nestor's mother seek out support groups for parents of children with learning disabilities.

- Rehabilitation and Treatment Responsiveness Interpretive Guidelines: The following interpretive statements reflect factors that may be relevant when considering a Client's likely responsiveness to institutionalization generally and to rehabilitation programs specifically as well as factors that may inform attempts to match individuals with the most appropriate treatment and rehabilitation modalities. Other individual-level factors not addressed by the PAI (e.g. intellectual abilities demographic characteristics) as well as various external/contextual-level factors (e.g. range of intervention options available therapist characteristics security/housing classification) may have a significant impact on the Client's willingness and/or ability to participate in and benefit from varying types of treatment and rehabilitative services and should be taken into consideration by the evaluating clinician. Unless otherwise noted scale elevation interpretations are based on community norms.

As noted earlier this Client's clinical scale profile elevation is more than one standard deviation above the mean clinical elevation observed in the Corrections normative sample. Eight of the clinical scales were significantly elevated suggesting that serious psychological maladjustment may interfere with this Client's ability to adapt to institutionalization. In terms of treatment amenability this Client acknowledged some problem areas in his life and expresses a generally positive attitude toward lifestyle changes and taking responsibility for his actions. Although typical of community adults in the PAI census-matched standardization sample his level of motivation is somewhat below average compared to offender samples. If participating in treatment programming such individuals tend to be more prone to non-compliance and resistance than other Clients. Treatment strategies oriented towards increasing motivation for change may be beneficial for this individual. Most or all Clients in correctional settings are likely to endorse antisocial attitudes values and beliefs to some extent. This individual's endorsement of these beliefs is elevated even when compared to other offenders (e.g. approximately 75% of the Corrections normative sample obtained a score of T < 70 on the ANT scale). Interventions aimed at reducing these criminogenic beliefs and cognitive distortions should be central components of rehabilitative efforts with this individual both in terms of reducing his likelihood of acting out while incarcerated and his likelihood of recidivating post-release. Assessment of psychopathy may also be useful in determining the potential utility of emotional interventions with this Client given his elevated ANT score. With respect to anger control issues the Client described himself as someone who is impatient and easily irritated. He may be somewhat quick-tempered and overly reactive to provocation. This rate of endorsement of anger control difficulties is somewhat uncommon compared to offender samples (e.g. approximately 70% of the Corrections normative sample obtained a score of T < 60 on the AGG scale). Interventions focused on anger management strategies may be beneficial for this individual in order for him to learn more prosocial means of conflict resolution and to adapt more effectively to a controlled institutional environment. This Client reported a relative lack of social supports in his life at this time. People who report low social support typically have few close personal relationships or are generally dissatisfied with the quality of those interpersonal relationships. Rehabilitative efforts should focus some effort on increasing this Client's network of prosocial associates and peers in the appropriate context.

## Recommendations for School

- Rec 1
- Rec 2
- Rec 3

## Recommendations for Home/Family

- Rec 1
- Rec 2
- Rec 3
